/**
 * transitions — small library of beat-aware style helpers for Remotion.
 *
 * Generated by the /beatmotion scaffold. Each helper takes the current frame
 * plus a beat or drop anchor and returns a CSSProperties-shaped style object
 * you can spread onto a div. Pure functions, no React state, idempotent.
 *
 *   import { useCurrentFrame, useVideoConfig } from "remotion";
 *   import { beatFade, dropPunch } from "./transitions";
 *
 *   const frame = useCurrentFrame();
 *   const { fps } = useVideoConfig();
 *   return (
 *     <div style={{ ...beatFade(frame, beats[2].frame, 8), ...dropPunch(frame, drops[0].frame) }}>
 *       hello
 *     </div>
 *   );
 */
import { interpolate, spring } from "remotion";

type Style = Record<string, string | number>;

/** Hard reveal at a beat — opacity 0 before, 1 at/after. */
export function beatCut(frame: number, beatFrame: number): Style {
  return { opacity: frame >= beatFrame ? 1 : 0 };
}

/** Fade in ending at the beat. `fadeFrames` controls the ramp length. */
export function beatFade(frame: number, beatFrame: number, fadeFrames = 10): Style {
  const opacity = interpolate(
    frame,
    [beatFrame - fadeFrames, beatFrame],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );
  return { opacity };
}

/**
 * Scale-bounce centered on a drop. `intensity` is the peak extra scale (0.15 = +15%).
 * `windowFrames` is the half-width of the bounce in frames.
 *
 * Kept for back-compat with hand-edited compositions. New scaffolds use
 * `dropClimax` instead, which is more visceral and composes correctly with
 * sibling transforms (returns {} when inactive rather than scale(1)).
 */
export function dropPunch(
  frame: number,
  dropFrame: number,
  intensity = 0.15,
  windowFrames = 8
): Style {
  const distance = Math.abs(frame - dropFrame);
  if (distance > windowFrames) return { transform: "scale(1)" };
  const t = 1 - distance / windowFrames;
  const scale = 1 + t * intensity;
  return { transform: `scale(${scale})` };
}

/**
 * Visceral drop emphasis composed of three temporal phases:
 *
 *   anticipation — `anticipationFrames` before the drop frame: subtle inverse
 *                  zoom-out + brightening, like the music ducking before the
 *                  hit. Mirrors what professional editors call a "tension cut."
 *   hit          — drop frame through `freezeFrames`: scale jumps to
 *                  `1 + scale`, optionally desaturated, brightness +30%. The
 *                  freeze gives the viewer's eye a beat to register the impact.
 *   release      — next `releaseFrames` frames: linear ramp back to scale 1
 *                  and full saturation.
 *
 * Returns `{}` outside any active phase so the element's other styles
 * (translate from sectionSlide, etc.) pass through cleanly. The previous
 * `dropPunch` returned `scale(1)` even when inactive, silently nuking any
 * other transform spread onto the same element.
 *
 * Default scale 0.4 (+40%) is intentionally large — the original 0.18 was
 * imperceptible against simultaneous fade/slide. If your hero element is
 * close to viewport edges, wrap it in an `overflow: visible` parent.
 */
export function dropClimax(
  frame: number,
  dropFrame: number,
  opts: {
    scale?: number;
    freezeFrames?: number;
    releaseFrames?: number;
    anticipationFrames?: number;
    desaturate?: boolean;
  } = {}
): Style {
  const scale = opts.scale ?? 0.4;
  const freezeFrames = opts.freezeFrames ?? 4;
  const releaseFrames = opts.releaseFrames ?? 12;
  const anticipationFrames = opts.anticipationFrames ?? 6;
  const desaturate = opts.desaturate ?? true;

  const d = frame - dropFrame; // signed

  // Anticipation: subtle inverse zoom + brighten in the run-up.
  if (d >= -anticipationFrames && d < 0) {
    const t = (d + anticipationFrames) / anticipationFrames; // 0 → 1 approaching drop
    return {
      transform: `scale(${(1 - 0.04 * t).toFixed(4)})`,
      filter: `brightness(${(1 + 0.1 * t).toFixed(3)})`,
    };
  }
  // Hit: scale punch + freeze + saturation pulse.
  if (d >= 0 && d < freezeFrames) {
    return {
      transform: `scale(${(1 + scale).toFixed(4)})`,
      filter: desaturate ? "saturate(0.2) brightness(1.3)" : "brightness(1.3)",
    };
  }
  // Release: linear ramp back to scale 1 and saturate 1.
  if (d >= freezeFrames && d < freezeFrames + releaseFrames) {
    const t = (d - freezeFrames) / releaseFrames; // 0 → 1
    const s = 1 + scale * (1 - t);
    const sat = 0.2 + 0.8 * t;
    const brt = 1.3 - 0.3 * t;
    return {
      transform: `scale(${s.toFixed(4)})`,
      filter: desaturate
        ? `saturate(${sat.toFixed(3)}) brightness(${brt.toFixed(3)})`
        : `brightness(${brt.toFixed(3)})`,
    };
  }
  // Inactive: no contribution. Element keeps whatever transform/filter it had.
  return {};
}

/**
 * Slide into place over the first few frames of a section. Uses a spring so the
 * motion feels musical, not linear. `distancePx` is the pre-spring offset.
 */
export function sectionSlide(
  frame: number,
  sectionStartFrame: number,
  fps: number,
  direction: "up" | "down" | "left" | "right" = "up",
  distancePx = 60
): Style {
  const local = Math.max(0, frame - sectionStartFrame);
  const t = spring({ frame: local, fps, config: { damping: 14, stiffness: 100 } });
  const offset = distancePx * (1 - t);
  switch (direction) {
    case "up":
      return { transform: `translateY(${offset}px)` };
    case "down":
      return { transform: `translateY(${-offset}px)` };
    case "left":
      return { transform: `translateX(${offset}px)` };
    case "right":
      return { transform: `translateX(${-offset}px)` };
  }
}

/**
 * Strength-aware transition picker. Given a beat's strength (0..1), return a
 * transition kind to apply. Used by the scaffold so strong beats get punchier
 * transitions than weak ones.
 *
 * Legacy API kept exported for back-compat with comps scaffolded before
 * Phase 2. New scaffolds prefer `pickTransitionPlan` which knows about
 * drum kind, downbeats, and phrase boundaries.
 */
export type TransitionKind = "cut" | "fade" | "slide";

export function pickTransition(strength: number): TransitionKind {
  if (strength >= 0.75) return "slide";
  if (strength >= 0.4) return "fade";
  return "cut";
}

// ───────────────────────────────────────────────────────────────────────
// Kind-idiomatic helpers — match the visual gesture to what the listener
// is hearing. Kicks land with a tight scale snap on the hero element,
// snares trigger a brief brightness flash (sounds + looks like a hit on a
// hi-energy frame), hi-hats nudge a small element by one pixel for the
// "tick tick" subdivision feel. Each returns {} outside its active window
// so they compose under spread without clobbering each other.
// ───────────────────────────────────────────────────────────────────────

/**
 * Sharp scale snap on a kick. Window is short (a few frames) and the scale
 * lerps linearly from `1 + intensity` at the beat frame back to 1 at the
 * window edge. Compose into a hero element that's wrapped in a parent
 * scale (e.g. dropClimax) without conflict — CSS transforms cascade
 * multiplicatively.
 */
export function kickPunch(
  frame: number,
  beatFrame: number,
  intensity: number = 0.05,
  windowFrames: number = 4
): Style {
  const d = frame - beatFrame;
  if (d < 0 || d > windowFrames) return {};
  const t = 1 - d / windowFrames;
  return { transform: `scale(${(1 + intensity * t).toFixed(4)})` };
}

/**
 * Brief brightness pulse on a snare. Decays linearly back to 1.0 over
 * `flashFrames`. Composes with other filter styles in CSS (each element's
 * filter applies independently — chained brightness multiplies).
 */
export function snareFlash(
  frame: number,
  beatFrame: number,
  flashFrames: number = 3,
  peak: number = 0.5
): Style {
  const d = frame - beatFrame;
  if (d < 0 || d > flashFrames) return {};
  const t = 1 - d / flashFrames;
  return { filter: `brightness(${(1 + peak * t).toFixed(3)})` };
}

/**
 * 1-pixel translation on a hi-hat. Settles back to 0 over `settleFrames`.
 * Pixels intentionally small — hats happen on every 8th note, and anything
 * more visible would look like a seizure. Route this to a small ornament
 * element (a corner badge, a tiny dot) so the eye reads "subdivisions are
 * happening" without the hero element constantly twitching.
 */
export function hatNudge(
  frame: number,
  beatFrame: number,
  pixels: number = 1,
  settleFrames: number = 2
): Style {
  const d = frame - beatFrame;
  if (d < 0 || d > settleFrames) return {};
  const t = 1 - d / settleFrames;
  return { transform: `translateX(${(pixels * t).toFixed(2)}px)` };
}

/**
 * Phrase-boundary slide-in. Bigger move than sectionSlide, longer settle.
 * Direction is derived from a numeric seed so adjacent phrases don't always
 * slide the same way — pass `phraseStartFrame` as the seed for that effect.
 */
export function phraseSlideIn(
  frame: number,
  phraseStartFrame: number,
  fps: number,
  seed: number = phraseStartFrame,
  distancePx: number = 120,
  durationFrames: number = 18
): Style {
  const local = frame - phraseStartFrame;
  if (local < 0) return {};
  if (local > durationFrames) return {};
  const dirs = ["up", "down", "left", "right"] as const;
  const dir = dirs[((seed * 2654435761) >>> 0) % 4];
  const t = local / durationFrames; // 0 → 1
  const ease = 1 - Math.pow(1 - t, 3); // ease-out cubic
  const offset = distancePx * (1 - ease);
  switch (dir) {
    case "up":
      return { transform: `translateY(${offset.toFixed(2)}px)` };
    case "down":
      return { transform: `translateY(${(-offset).toFixed(2)}px)` };
    case "left":
      return { transform: `translateX(${offset.toFixed(2)}px)` };
    case "right":
      return { transform: `translateX(${(-offset).toFixed(2)}px)` };
  }
}

/**
 * Richer Beat shape used by `pickTransitionPlan`. All structural fields are
 * optional so legacy sidecars degrade gracefully — without `kind`/`downbeat`
 * the picker falls back to a strength-based fade.
 */
export type Beat = {
  time: number;
  frame: number;
  strength: number;
  kind?: "kick" | "snare" | "hat" | "other";
  barPos?: 1 | 2 | 3 | 4;
  phrasePos?: number;
  downbeat?: boolean;
};

export type TransitionPlan = {
  primary: "cut" | "fade" | "punch" | "flash" | "nudge" | "climax" | "slide";
  intensity?: number;
  fadeFrames?: number;
  pixels?: number;
};

/**
 * Pick a transition plan from a beat + context flags. Decision order:
 *
 *   1. isDrop → climax (the moment carries the most weight)
 *   2. isPhraseStart → slide (16/32-beat punctuation)
 *   3. downbeat → punch (musically the most important beat of the bar)
 *   4. by drum kind: kick → punch, snare → flash, hat → nudge
 *   5. unknown → strength-weighted fade (legacy behaviour)
 */
export function pickTransitionPlan(
  beat: Beat | null,
  opts: { isDrop?: boolean; isPhraseStart?: boolean } = {}
): TransitionPlan {
  if (opts.isDrop) return { primary: "climax", intensity: 0.4 };
  if (opts.isPhraseStart) return { primary: "slide", fadeFrames: 14 };
  if (!beat) return { primary: "cut" };
  if (beat.downbeat) return { primary: "punch", intensity: 0.08 };
  switch (beat.kind) {
    case "kick":  return { primary: "punch", intensity: 0.05 };
    case "snare": return { primary: "flash", fadeFrames: 3 };
    case "hat":   return { primary: "nudge", pixels: 1 };
    case "other":
    case undefined:
    default:      return { primary: "fade", fadeFrames: Math.max(2, Math.round(8 * (beat.strength ?? 0))) };
  }
}

// ───────────────────────────────────────────────────────────────────────
// Motion-graphics-grade primitives. These replace the "react on every beat"
// pattern with structural choreography — anticipation, impact, settle.
// Use these for title / promo scaffolds; the older per-beat helpers above
// are kept for back-compat but tend to produce twitchy results on real
// music because they fire on every detected hit.
// ───────────────────────────────────────────────────────────────────────

export type DropImpactStyles = {
  /** Camera shake + scale, spread onto the OUTER element (wraps everything). */
  cameraStyle: Style;
  /** Full-screen white flash, spread onto an AbsoluteFill child with pointer-events: none. */
  flashStyle: Style;
  /** Background dim for the anticipation window. */
  vignetteStyle: Style;
};

/**
 * Multi-stage drop choreography: 12-frame anticipation dip → 4-frame
 * camera-shake + flash + scale impact → 26-frame ease-out settle with
 * overshoot decay. Designed to FEEL like a drop, not just register one.
 *
 * Spread `cameraStyle` onto the element that wraps your composition (the
 * outer AbsoluteFill). Spread `flashStyle` onto a pointerEvents:none child
 * that fills the frame. The vignette is optional — spread onto a separate
 * full-frame backdrop if you want the anticipation darkening.
 *
 * Reference: this is the "explosive drop" pattern used in title sequences
 * and promo videos — the impact reads cleanly across drum-and-bass, EDM,
 * and trap drops alike.
 */
export function dropImpact(
  frame: number,
  dropFrame: number,
  opts: {
    intensity?: number;       // 0..1 scaling on the whole effect
    anticipationFrames?: number;
    hitFrames?: number;
    settleFrames?: number;
    shakeAmplitude?: number;  // px, peak shake during hit
    scalePeak?: number;       // peak extra scale during hit (0.15 = +15%)
    flashStrength?: number;   // 0..1, peak opacity of white flash
  } = {}
): DropImpactStyles {
  const intensity = opts.intensity ?? 1;
  const anticipationFrames = opts.anticipationFrames ?? 12;
  const hitFrames = opts.hitFrames ?? 4;
  const settleFrames = opts.settleFrames ?? 26;
  const shakeAmp = opts.shakeAmplitude ?? 6;
  const scalePeak = opts.scalePeak ?? 0.15;
  const flashStrength = opts.flashStrength ?? 0.45;

  const d = frame - dropFrame;
  const empty: DropImpactStyles = {
    cameraStyle: {},
    flashStyle: { background: "rgba(255,255,255,0)" },
    vignetteStyle: { background: "rgba(0,0,0,0)" },
  };

  // Phase 1 — anticipation: subtle inverse zoom + vignette darkening.
  if (d >= -anticipationFrames && d < 0) {
    const t = (d + anticipationFrames) / anticipationFrames; // 0 → 1 approaching impact
    return {
      cameraStyle: { transform: `scale(${(1 - 0.025 * intensity * t).toFixed(4)})` },
      flashStyle: { background: "rgba(255,255,255,0)" },
      vignetteStyle: { background: `rgba(0,0,0,${(0.08 * t * intensity).toFixed(3)})` },
    };
  }

  // Phase 2 — impact: scale punch + camera shake + white flash.
  if (d >= 0 && d < hitFrames) {
    const decay = 1 - d / hitFrames;
    const shake = shakeAmp * intensity * decay;
    // Pseudo-random shake derived from frame index — deterministic per frame.
    const shakeX = Math.sin(d * 7.3) * shake;
    const shakeY = Math.cos(d * 5.1) * shake;
    const rotate = Math.sin(d * 11.0) * 0.6 * intensity * decay;
    const scale = 1 + scalePeak * intensity;
    return {
      cameraStyle: {
        transform: `translate(${shakeX.toFixed(2)}px, ${shakeY.toFixed(2)}px) rotate(${rotate.toFixed(3)}deg) scale(${scale.toFixed(4)})`,
      },
      flashStyle: {
        background: `rgba(255,255,255,${(flashStrength * intensity * decay).toFixed(3)})`,
      },
      vignetteStyle: { background: "rgba(0,0,0,0)" },
    };
  }

  // Phase 3 — settle: ease-out cubic from scalePeak back to 1, no shake.
  if (d >= hitFrames && d < hitFrames + settleFrames) {
    const t = (d - hitFrames) / settleFrames;
    const ease = 1 - Math.pow(1 - t, 3);
    const residual = scalePeak * intensity * (1 - ease);
    return {
      cameraStyle: { transform: `scale(${(1 + residual).toFixed(4)})` },
      flashStyle: { background: "rgba(255,255,255,0)" },
      vignetteStyle: { background: "rgba(0,0,0,0)" },
    };
  }

  return empty;
}

/**
 * Kinetic-typography letter reveal. For each character index, returns the
 * style at the current `revealProgress` (0..1) using a staggered offset
 * per letter. Letters slide up from 40px below with opacity fade-in.
 *
 *   text.split("").map((c, i) => {
 *     const style = kineticLetter(i, revealProgress, text.length);
 *     return <span style={{display: "inline-block", ...style}}>{c}</span>;
 *   })
 */
export function kineticLetter(
  charIndex: number,
  revealProgress: number,
  totalChars: number,
  opts: { staggerFrac?: number; travelPx?: number } = {}
): Style {
  const staggerFrac = opts.staggerFrac ?? 0.5; // each letter starts 50% into the previous one
  const travelPx = opts.travelPx ?? 40;
  // Span the reveal across the full progress range with overlapping windows.
  const perLetter = 1 / Math.max(1, totalChars * staggerFrac);
  const start = charIndex * perLetter * staggerFrac;
  const t = Math.max(0, Math.min(1, (revealProgress - start) / Math.max(0.001, perLetter)));
  // Ease-out cubic for the slide and opacity.
  const ease = 1 - Math.pow(1 - t, 3);
  return {
    transform: `translateY(${((1 - ease) * travelPx).toFixed(2)}px)`,
    opacity: ease.toFixed(3),
  };
}

/**
 * Width of an animated accent line, spring-easing from 0 to maxPx over
 * the first `holdFrames` of a phrase. Use under titles to visually
 * underline the section reveal.
 */
export function accentLineWidth(
  frame: number,
  startFrame: number,
  fps: number,
  maxPx: number = 280,
  delayFrames: number = 8
): number {
  const local = frame - startFrame - delayFrames;
  if (local < 0) return 0;
  const t = spring({
    frame: local,
    fps,
    config: { damping: 16, stiffness: 110, mass: 0.9 },
  });
  return Math.max(0, Math.min(maxPx, maxPx * t));
}

/**
 * Subtle background pulse at downbeats — radial-gradient brightness ramps
 * up briefly when a downbeat fires, then decays over 8 frames. Used by
 * BackgroundLayer in the title scaffold to give the impression that the
 * background is "breathing" with the music without anything visible
 * actually moving.
 */
export function downbeatPulse(
  frame: number,
  lastDownbeatFrame: number | null,
  opts: { decayFrames?: number; peak?: number } = {}
): number {
  if (lastDownbeatFrame === null || frame < lastDownbeatFrame) return 0;
  const decayFrames = opts.decayFrames ?? 8;
  const peak = opts.peak ?? 0.04;
  const d = frame - lastDownbeatFrame;
  if (d > decayFrames) return 0;
  return peak * (1 - d / decayFrames);
}

// ─────────────────────────────────────────────────────────────────────────
// Phase 5 atmospheric / continuous-driver helpers.
//
// These primitives don't fire on discrete events. They take continuous
// audio drivers (intensity, tension, subBass, hiAir, centroid) from
// `useBeats.*At(frame)` and return CSS style fragments that subtly modulate
// the frame at all times. The goal: most frames have continuous motion
// driven by the audio's continuous properties, with discrete events
// (drops, phrase starts) as punctuation on top.
// ─────────────────────────────────────────────────────────────────────────

/**
 * Slow continuous parallax drift. Translates an element by a smooth
 * sinusoidal offset whose amplitude is modulated by `intensity` (0..1).
 * Bigger intensity → bigger drift. Used on background layers to give them
 * an atmospheric "breathing" quality even during silent passages.
 *
 *   speed   — radians per second of the drift sinusoid (0.3 = slow, 1.2 = busy)
 *   maxPx   — peak amplitude in pixels at intensity = 1.0
 *   axis    — "x" / "y" / "xy" (xy = elliptical orbit)
 */
export function parallaxDrift(
  frame: number,
  fps: number,
  intensity: number,
  opts: { speed?: number; maxPx?: number; axis?: "x" | "y" | "xy"; phase?: number } = {}
): Style {
  const speed = opts.speed ?? 0.4;
  const maxPx = opts.maxPx ?? 14;
  const axis = opts.axis ?? "xy";
  const phase = opts.phase ?? 0;
  const t = (frame / fps) * speed + phase;
  const amp = maxPx * Math.max(0, Math.min(1, intensity));
  const dx = axis === "y" ? 0 : Math.sin(t) * amp;
  const dy = axis === "x" ? 0 : Math.cos(t * 0.7) * amp;
  return { transform: `translate(${dx.toFixed(2)}px, ${dy.toFixed(2)}px)` };
}

/**
 * Barely-visible chromatic aberration — text-shadow with red and blue offsets.
 * Driven by `tension` (0..1). At tension 0, returns no shadow (clean). At
 * tension 1, applies ~3px offset of red + blue channels. Reads as cinematic
 * when subtle.
 *
 * Apply to hero typography. Keep maxOffset ≤ 3px or it looks broken.
 */
export function chromaticAberration(tension: number, maxOffset: number = 3): Style {
  const t = Math.max(0, Math.min(1, tension));
  if (t < 0.05) return {};
  const off = t * maxOffset;
  return {
    textShadow: `${(-off).toFixed(2)}px 0 rgba(255,80,80,0.7), ${off.toFixed(2)}px 0 rgba(80,140,255,0.7)`,
  };
}

/**
 * Sub-bass-driven warm glow. Applies a `box-shadow` aura whose radius and
 * opacity scale with `subBass` (0..1). Use on the hero title block so the
 * bass HITS visually punch the typography.
 *
 *   color   — RGB triplet hex string (no leading #)
 *   maxRadius — peak shadow radius in px at subBass=1.0
 */
export function glowAura(
  subBass: number,
  color: string = "FFFFFF",
  maxRadius: number = 80
): Style {
  const t = Math.max(0, Math.min(1, subBass));
  if (t < 0.05) return {};
  const radius = t * maxRadius;
  const spread = t * 4;
  const opacity = t * 0.4;
  // Convert "FFFFFF" → "255,255,255".
  const r = parseInt(color.slice(0, 2), 16);
  const g = parseInt(color.slice(2, 4), 16);
  const b = parseInt(color.slice(4, 6), 16);
  return {
    boxShadow: `0 0 ${radius.toFixed(1)}px ${spread.toFixed(1)}px rgba(${r},${g},${b},${opacity.toFixed(3)})`,
  };
}

/**
 * Edge vignette that intensifies on tension. Static gradient that just
 * gets denser when tension is high. Use on a full-frame AbsoluteFill
 * overlay to darken the edges, focusing attention on the center.
 */
export function vignetteEdge(tension: number, opts: { maxOpacity?: number } = {}): Style {
  const max = opts.maxOpacity ?? 0.5;
  const t = Math.max(0, Math.min(1, tension));
  const opacity = t * max;
  if (opacity < 0.02) return {};
  return {
    background: `radial-gradient(circle at 50% 50%, transparent 50%, rgba(0,0,0,${opacity.toFixed(3)}) 100%)`,
  };
}

/**
 * Static grain noise overlay. Returns a `background-image` data URL
 * containing an inline SVG with a `feTurbulence` filter, which the browser
 * rasterizes into actual noise. Avoids per-frame computation entirely;
 * one static asset that hides flat-color banding and gives the frame a
 * premium "film grain" texture.
 *
 *   opacity — 0..1, default 0.03 (3%, barely visible)
 *   seed    — turbulence seed; change to get a different grain pattern
 */
export function grainNoise(opacity: number = 0.03, seed: number = 7): Style {
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' width='200' height='200'><filter id='n'><feTurbulence type='fractalNoise' baseFrequency='0.95' numOctaves='2' stitchTiles='stitch' seed='${seed}'/><feColorMatrix values='0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 ${opacity} 0'/></filter><rect width='100%' height='100%' filter='url(%23n)'/></svg>`;
  // URL-encode # so it stays a valid data URL.
  const encoded = encodeURIComponent(svg).replace(/'/g, "%27");
  return {
    backgroundImage: `url("data:image/svg+xml;utf8,${encoded}")`,
    backgroundRepeat: "repeat",
    opacity: 1,
  };
}

/**
 * Hue rotation derived from spectral centroid. As the music's spectral
 * center of mass shifts (warm/dark to bright), the hue rotates ±degMax
 * degrees from a neutral 0. Use on background gradients to give the frame
 * a colorshift that tracks the music's timbre.
 */
export function hueShiftFromCentroid(
  centroid: number,
  opts: { degMax?: number } = {}
): Style {
  const max = opts.degMax ?? 8;
  const t = Math.max(0, Math.min(1, centroid));
  // Center the rotation around 0 — centroid 0.5 → 0deg rotation.
  const deg = (t - 0.5) * max * 2;
  if (Math.abs(deg) < 0.5) return {};
  return { filter: `hue-rotate(${deg.toFixed(2)}deg)` };
}

/**
 * Camera dolly: subtle continuous scale modulation driven by intensity.
 * Returns a transform with scale `1 + intensity * amp`. Use on the camera
 * group so the WHOLE composition gently zooms in on loud sections and
 * pulls back during quiet sections.
 *
 * Different from dropImpact's discrete punch — this is the continuous
 * "we're in a loud part of the song" signal.
 */
export function cameraDolly(intensity: number, amp: number = 0.025): Style {
  const t = Math.max(0, Math.min(1, intensity));
  const scale = 1 + t * amp;
  return { transform: `scale(${scale.toFixed(4)})` };
}
