/**
 * transitions — small library of beat-aware style helpers for Remotion.
 *
 * Generated by the /beatmotion scaffold. Each helper takes the current frame
 * plus a beat or drop anchor and returns a CSSProperties-shaped style object
 * you can spread onto a div. Pure functions, no React state, idempotent.
 *
 *   import { useCurrentFrame, useVideoConfig } from "remotion";
 *   import { beatFade, dropPunch } from "./transitions";
 *
 *   const frame = useCurrentFrame();
 *   const { fps } = useVideoConfig();
 *   return (
 *     <div style={{ ...beatFade(frame, beats[2].frame, 8), ...dropPunch(frame, drops[0].frame) }}>
 *       hello
 *     </div>
 *   );
 */
import { interpolate, spring } from "remotion";

type Style = Record<string, string | number>;

/** Hard reveal at a beat — opacity 0 before, 1 at/after. */
export function beatCut(frame: number, beatFrame: number): Style {
  return { opacity: frame >= beatFrame ? 1 : 0 };
}

/** Fade in ending at the beat. `fadeFrames` controls the ramp length. */
export function beatFade(frame: number, beatFrame: number, fadeFrames = 10): Style {
  const opacity = interpolate(
    frame,
    [beatFrame - fadeFrames, beatFrame],
    [0, 1],
    { extrapolateLeft: "clamp", extrapolateRight: "clamp" }
  );
  return { opacity };
}

/**
 * Scale-bounce centered on a drop. `intensity` is the peak extra scale (0.15 = +15%).
 * `windowFrames` is the half-width of the bounce in frames.
 */
export function dropPunch(
  frame: number,
  dropFrame: number,
  intensity = 0.15,
  windowFrames = 8
): Style {
  const distance = Math.abs(frame - dropFrame);
  if (distance > windowFrames) return { transform: "scale(1)" };
  const t = 1 - distance / windowFrames;
  const scale = 1 + t * intensity;
  return { transform: `scale(${scale})` };
}

/**
 * Slide into place over the first few frames of a section. Uses a spring so the
 * motion feels musical, not linear. `distancePx` is the pre-spring offset.
 */
export function sectionSlide(
  frame: number,
  sectionStartFrame: number,
  fps: number,
  direction: "up" | "down" | "left" | "right" = "up",
  distancePx = 60
): Style {
  const local = Math.max(0, frame - sectionStartFrame);
  const t = spring({ frame: local, fps, config: { damping: 14, stiffness: 100 } });
  const offset = distancePx * (1 - t);
  switch (direction) {
    case "up":
      return { transform: `translateY(${offset}px)` };
    case "down":
      return { transform: `translateY(${-offset}px)` };
    case "left":
      return { transform: `translateX(${offset}px)` };
    case "right":
      return { transform: `translateX(${-offset}px)` };
  }
}

/**
 * Strength-aware transition picker. Given a beat's strength (0..1), return a
 * transition kind to apply. Used by the scaffold so strong beats get punchier
 * transitions than weak ones.
 */
export type TransitionKind = "cut" | "fade" | "slide";

export function pickTransition(strength: number): TransitionKind {
  if (strength >= 0.75) return "slide";
  if (strength >= 0.4) return "fade";
  return "cut";
}
