/**
 * useBeats — Remotion-friendly helpers for working with a beatmotion sidecar.
 *
 * Generated by the /beatmotion skill. Place this file next to your composition
 * and import it like:
 *
 *   import beatsData from "./song.beats.json";
 *   import { createBeatHelpers } from "./useBeats";
 *   const beats = createBeatHelpers(beatsData);
 *
 * Then in your component:
 *
 *   const frame = useCurrentFrame();
 *   const opacity = interpolate(frame, [0, beats.frameOf(2)], [0, 1]);
 *   if (beats.isOnDrop(frame)) // ...
 *
 * Or use the React hook variant if you have a single sidecar per composition:
 *
 *   const beats = useBeats(beatsData);
 */

export type BeatKind = "kick" | "snare" | "hat" | "other";

export type Beat = {
  time: number;
  frame: number;
  strength: number;
  // Optional musical-structure fields populated by Phase 2+ analyzer.
  // Absent on legacy sidecars — helpers degrade gracefully.
  // Note: `kind` is typed `string` (not the literal union) so that values
  // imported from JSON sidecars assign cleanly — TS narrows the literal
  // union away on JSON import. Helpers still compare against the literal
  // values "kick" / "snare" / "hat" / "other" at runtime.
  kind?: string;
  barPos?: number;
  phrasePos?: number;
  downbeat?: boolean;
  synthetic?: boolean;
  manualOverride?: boolean;
  segment?: number;
  bandEnergies?: number[];
  attackBacktrackMs?: number;
};
export type Drop = { time: number; frame: number; kind: string };
export type Section = { start: number; end: number; kind: string };

export type Classification = {
  genre: string;
  bpmClass: string;
  subBassClass: string;
  brightClass: string;
  grooveClass: string;
  intensityProfile: string;
  confidence: number;
};

export type SpectralBundle = {
  fps: number;
  centroid: number[];
  spread: number[];
  rolloff: number[];
  flux: number[];
  flatness: number[];
};

export type EnvelopesBundle = {
  fps: number;
  total: number[];
  subBass: number[];
  lowBody: number[];
  midBody: number[];
  midBright: number[];
  hiAir: number[];
};

export type IntensityBundle = {
  fps: number;
  energy: number[];
  intensity: number[];
  tension: number[];
  density: number[];
};

export type BeatsData = {
  audio: string;
  duration: number;
  fps: number;
  bpm: number;
  beats: Beat[];
  drops: Drop[];
  sections: Section[];
  overrides?: unknown[];
  // Phase 3 additions (optional).
  gridLocked?: boolean;
  phrases?: Array<{ startBeat: number; endBeat: number; startFrame: number; endFrame: number }>;
  // Phase 5 additions (optional).
  classification?: Classification;
  spectral?: SpectralBundle;
  envelopes?: EnvelopesBundle;
  intensity?: IntensityBundle;
};

export type BestBeatOpts = {
  downbeatBonus?: number;
  barOneBonus?: number;
  phraseBonus?: number;
  kickBoost?: number;
  manualOverrideBonus?: number;
  distancePenalty?: number;
};

export type BestBeatResult = {
  idx: number;
  deltaFrames: number;
  score: number;
};

export type Phrase = {
  startBeat: number;
  endBeat: number;
  startFrame: number;
  endFrame: number;
};

export type BeatHelpers = {
  raw: BeatsData;
  bpm: number;
  fps: number;
  beats: Beat[];
  drops: Drop[];
  sections: Section[];
  /** Inferred phrase boundaries (every 16 or 32 beats). Empty unless grid-locked. */
  phrases: Phrase[];
  /** True when the analyzer locked beats to a tempo grid. */
  gridLocked: boolean;

  /** Frame of the Nth detected beat, with bounds clamping. */
  frameOf: (beatIndex: number) => number;

  /** Time (s) of the Nth detected beat. */
  timeOf: (beatIndex: number) => number;

  /** Index of the beat nearest the given frame (pure frame distance). */
  nearestBeat: (frame: number) => number;

  /**
   * Index of the musically best-fit beat for the given frame. Weights by
   * strength, downbeat / bar-position / phrase-start / kick bonuses, and a
   * distance penalty. Defaults to a strength-weighted nearest picker when
   * the sidecar lacks structure fields.
   */
  bestBeat: (frame: number, opts?: BestBeatOpts) => BestBeatResult;

  /** Frame of the next beat at or after the given frame, or Infinity if none. */
  nextBeatFrame: (frame: number) => number;

  /** Frame of the previous beat at or before the given frame, or -Infinity if none. */
  prevBeatFrame: (frame: number) => number;

  /** True if the given frame is within `tolerance` frames of any beat. */
  isOnBeat: (frame: number, tolerance?: number) => boolean;

  /** True if the given frame is within `tolerance` frames of any drop. */
  isOnDrop: (frame: number, tolerance?: number) => boolean;

  /** The section containing the given frame, or null. */
  sectionAt: (frame: number) => Section | null;

  /** The main_drop entry, if one exists. */
  mainDrop: () => Drop | null;

  // ─── Phase 5: continuous driver lookups (graceful fallback to 0) ───
  /** Normalized smoothed energy curve, 0..1. Slow-changing "is the track loud right now". */
  energyAt: (frame: number) => number;
  /** Long-smoothed intensity, 0..1. For atmospheric drivers that shouldn't twitch. */
  intensityAt: (frame: number) => number;
  /** Tension curve (flux + centroid derivative), 0..1. For anticipation effects. */
  tensionAt: (frame: number) => number;
  /** Onset density curve, 0..1. For "how busy is the rhythm". */
  densityAt: (frame: number) => number;
  /** Sub-bass envelope, 0..1. For bass-driven glow / scale. */
  subBassAt: (frame: number) => number;
  /** Hi-air envelope, 0..1. For shimmer / sparkle / hi-band particles. */
  hiAirAt: (frame: number) => number;
  /** Spectral centroid normalized to [0..1] against Nyquist. For color / brightness drivers. */
  centroidAt: (frame: number) => number;
  /** Raw FPS-rate spectral flux at this frame. For chromatic aberration / transitions. */
  fluxAt: (frame: number) => number;
  /** Spectral flatness 0..1. Tonal vs noisy. */
  flatnessAt: (frame: number) => number;
  /** Classification object (genre + axis labels). undefined on legacy sidecars. */
  classification?: Classification;
};

export function createBeatHelpers(data: BeatsData): BeatHelpers {
  const beats = [...data.beats].sort((a, b) => a.frame - b.frame);
  const drops = [...data.drops].sort((a, b) => a.frame - b.frame);
  const sections = data.sections ?? [];
  const phrases = data.phrases ?? [];
  const gridLocked = data.gridLocked === true;

  const frameOf = (i: number): number => {
    if (beats.length === 0) return 0;
    const clamped = Math.max(0, Math.min(beats.length - 1, i));
    return beats[clamped].frame;
  };

  const timeOf = (i: number): number => {
    if (beats.length === 0) return 0;
    const clamped = Math.max(0, Math.min(beats.length - 1, i));
    return beats[clamped].time;
  };

  const nearestBeat = (frame: number): number => {
    if (beats.length === 0) return -1;
    // Linear scan is fine; beat counts are small (typical 100-500 per song).
    let bestIdx = 0;
    let bestDist = Infinity;
    for (let i = 0; i < beats.length; i++) {
      const d = Math.abs(beats[i].frame - frame);
      if (d < bestDist) {
        bestDist = d;
        bestIdx = i;
      }
    }
    return bestIdx;
  };

  // Musically-aware picker — same scoring rule as bin/sync.ts:bestBeatForFrame.
  // Bonuses default to 0 when their corresponding field is absent on a beat,
  // so on legacy sidecars this degrades cleanly to strength-weighted nearest.
  const bestBeat = (frame: number, opts: BestBeatOpts = {}): BestBeatResult => {
    if (beats.length === 0) return { idx: -1, deltaFrames: 0, score: 0 };
    const downbeatBonus = opts.downbeatBonus ?? 1.5;
    const barOneBonus = opts.barOneBonus ?? 0.5;
    const phraseBonus = opts.phraseBonus ?? 0.8;
    const kickBoost = opts.kickBoost ?? 0.3;
    const manualOverrideBonus = opts.manualOverrideBonus ?? 2.0;
    const distancePenalty = opts.distancePenalty ?? 0.1;

    let bestIdx = 0;
    let bestScore = -Infinity;
    for (let i = 0; i < beats.length; i++) {
      const b = beats[i];
      const delta = Math.abs(b.frame - frame);
      let bonus = 1;
      if (b.downbeat) bonus += downbeatBonus;
      if (b.barPos === 1) bonus += barOneBonus;
      if (b.phrasePos === 0) bonus += phraseBonus;
      if (b.kind === "kick") bonus += kickBoost;
      if (b.manualOverride) bonus += manualOverrideBonus;
      const score = ((b.strength ?? 0) + 0.1) * bonus / (1 + distancePenalty * delta);
      if (score > bestScore) {
        bestScore = score;
        bestIdx = i;
      }
    }
    return { idx: bestIdx, deltaFrames: beats[bestIdx].frame - frame, score: bestScore };
  };

  const nextBeatFrame = (frame: number): number => {
    for (const b of beats) if (b.frame >= frame) return b.frame;
    return Infinity;
  };

  const prevBeatFrame = (frame: number): number => {
    let best = -Infinity;
    for (const b of beats) {
      if (b.frame <= frame && b.frame > best) best = b.frame;
    }
    return best;
  };

  const isOnBeat = (frame: number, tolerance = 1): boolean => {
    for (const b of beats) if (Math.abs(b.frame - frame) <= tolerance) return true;
    return false;
  };

  const isOnDrop = (frame: number, tolerance = 1): boolean => {
    for (const d of drops) if (Math.abs(d.frame - frame) <= tolerance) return true;
    return false;
  };

  const sectionAt = (frame: number): Section | null => {
    const time = frame / data.fps;
    for (const s of sections) if (time >= s.start && time < s.end) return s;
    return null;
  };

  const mainDrop = (): Drop | null => drops.find((d) => d.kind === "main_drop") ?? null;

  // Phase 5 continuous drivers. `array[frame]` lookups with bounds clamping.
  // Returns 0 on legacy sidecars (or undefined frames) so templates degrade
  // safely without conditional checks at every callsite.
  const safeAt = (arr: number[] | undefined, frame: number): number => {
    if (!arr || arr.length === 0) return 0;
    const i = Math.max(0, Math.min(arr.length - 1, Math.floor(frame)));
    return arr[i] ?? 0;
  };
  // Centroid normalized to Nyquist so callers get a stable 0..1 regardless of
  // sample rate. 22kHz Nyquist (44.1k sr) divides by 22050; 24kHz Nyquist by
  // 24000.
  const nyquist = 22050; // pessimistic default; real Nyquist depends on song sr
  const centroidAt = (frame: number): number => {
    const hz = safeAt(data.spectral?.centroid, frame);
    return Math.max(0, Math.min(1, hz / nyquist));
  };
  const energyAt = (frame: number): number => safeAt(data.intensity?.energy, frame);
  const intensityAt = (frame: number): number => safeAt(data.intensity?.intensity, frame);
  const tensionAt = (frame: number): number => safeAt(data.intensity?.tension, frame);
  const densityAt = (frame: number): number => safeAt(data.intensity?.density, frame);
  const subBassAt = (frame: number): number => safeAt(data.envelopes?.subBass, frame);
  const hiAirAt = (frame: number): number => safeAt(data.envelopes?.hiAir, frame);
  const fluxAt = (frame: number): number => {
    // Normalize raw flux against its observed maximum across the song.
    const arr = data.spectral?.flux;
    if (!arr || arr.length === 0) return 0;
    let max = 0;
    for (const v of arr) if (v > max) max = v;
    if (max <= 0) return 0;
    return safeAt(arr, frame) / max;
  };
  const flatnessAt = (frame: number): number => safeAt(data.spectral?.flatness, frame);

  return {
    raw: data,
    bpm: data.bpm,
    fps: data.fps,
    beats,
    drops,
    sections,
    phrases,
    gridLocked,
    frameOf,
    timeOf,
    nearestBeat,
    bestBeat,
    nextBeatFrame,
    prevBeatFrame,
    isOnBeat,
    isOnDrop,
    sectionAt,
    mainDrop,
    energyAt,
    intensityAt,
    tensionAt,
    densityAt,
    subBassAt,
    hiAirAt,
    centroidAt,
    fluxAt,
    flatnessAt,
    classification: data.classification,
  };
}

/**
 * React hook variant — memoizes the helpers per BeatsData reference.
 * Import `useMemo` from React in your project if you use this.
 */
export function useBeats(data: BeatsData): BeatHelpers {
  // Lazy-require React's useMemo to keep this file dependency-free for tests.
  // In a Remotion project, React is always present.
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { useMemo } = require("react") as { useMemo: <T>(fn: () => T, deps: unknown[]) => T };
  return useMemo(() => createBeatHelpers(data), [data]);
}
