import { describe, expect, test } from "bun:test";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { FIXTURES, runBin, withTmpDir } from "./helpers.ts";

// Mock-real-music fixture: 24 bars at 128 BPM with kick on 1+3, snare on 2+4,
// hat 8ths, white-noise riser through build, and a drop at bar 9 (15.0 s).
// Generated by scripts/gen-real-fixture.ts; truth file ships alongside.
const FIXTURE_WAV = "mock-128bpm-chorus.wav";
const FIXTURE_TRUTH = "mock-128bpm-chorus.truth.json";

describe("analyze on mock real-music fixture", () => {
  test("detects musical structure within tolerance", async () => {
    await withTmpDir(async (dir) => {
      const outPath = join(dir, "out.beats.json");
      const result = await runBin("analyze.ts", [
        join(FIXTURES, FIXTURE_WAV),
        "--out",
        outPath,
      ]);
      expect(result.exitCode).toBe(0);
      const beats = JSON.parse(await readFile(outPath, "utf8"));
      const truth = JSON.parse(await readFile(join(FIXTURES, FIXTURE_TRUTH), "utf8"));

      // BPM within ±2 of 128 (octave correction must trigger — raw AC peaks
      // strongest at 64 BPM because of the kick-on-1+3 pattern).
      expect(Math.abs(beats.bpm - truth.bpm)).toBeLessThanOrEqual(2);

      // Grid must lock for a track this regular.
      expect(beats.gridLocked).toBe(true);

      // At least 80 real beats detected (truth has 232 events spread across
      // kicks + snares + hats; many hats are merged by minIntervalFrames).
      const realBeats = beats.beats.filter((b: { synthetic?: boolean }) => !b.synthetic);
      expect(realBeats.length).toBeGreaterThanOrEqual(80);

      // Phrases inferred (16-beat phrases over a 32-second drop section
      // should produce at least 4 phrase entries).
      expect(beats.phrases.length).toBeGreaterThanOrEqual(4);

      // At least one downbeat detected.
      const downbeats = beats.beats.filter(
        (b: { downbeat?: boolean }) => b.downbeat
      );
      expect(downbeats.length).toBeGreaterThanOrEqual(2);

      // Some kind diversity — kicks, snares, hats all present (allow that
      // the classifier won't perfectly hit "kick" vs "snare" on every hit
      // since the synthesized timbres aren't sharp drum samples, but it
      // should pick up the hi-hat air band readily).
      const kinds = new Set(realBeats.map((b: { kind?: string }) => b.kind));
      expect(kinds.size).toBeGreaterThanOrEqual(2);

      // At least one drop detected. Drop accuracy on the mock fixture is
      // intentionally loose: the white-noise riser dominates energy through
      // the build section, so the analyzer's energy-crossing approach can
      // fire several seconds before the true drop at 15 s. Future work:
      // a brightness-fall-edge detector that catches the moment the riser
      // cuts out. For now we just verify at least one drop is reported.
      expect(beats.drops.length).toBeGreaterThanOrEqual(1);

      // ─── Phase 5 sidecar fields ───
      expect(beats.analyzer.version).toBe("0.6.0-spectral");
      const expectedFrames = Math.round(beats.duration * beats.fps);
      // Allow ±2 frames slack — duration float rounding.
      const checkLen = (arr: number[]) => {
        expect(arr.length).toBeGreaterThanOrEqual(expectedFrames - 2);
        expect(arr.length).toBeLessThanOrEqual(expectedFrames + 2);
      };
      expect(beats.spectral).toBeDefined();
      checkLen(beats.spectral.centroid);
      checkLen(beats.spectral.flux);
      checkLen(beats.spectral.flatness);
      checkLen(beats.spectral.rolloff);
      checkLen(beats.spectral.spread);
      expect(beats.envelopes).toBeDefined();
      checkLen(beats.envelopes.total);
      checkLen(beats.envelopes.subBass);
      checkLen(beats.envelopes.hiAir);
      expect(beats.intensity).toBeDefined();
      checkLen(beats.intensity.energy);
      checkLen(beats.intensity.tension);
      checkLen(beats.intensity.density);
      expect(beats.classification).toBeDefined();
      expect(typeof beats.classification.genre).toBe("string");
      expect(typeof beats.classification.bpmClass).toBe("string");
      // Energy at a frame near the drop should be high (track is loud there).
      const dropFrame = Math.round(15 * beats.fps); // truth drop time ~15s for mock fixture
      const dropEnergy = beats.intensity.energy[Math.min(dropFrame, beats.intensity.energy.length - 1)];
      expect(dropEnergy).toBeGreaterThan(0.3);
    });
  });
});
